### ISSUE TITLE
Launch Image 수정

### ISSUE THREAD

**Issue by YimKeul** [CNUBasicProjectLab/ToD#9]
피그마에 새로운 Launch Image업로드 함.

적용해주기!

**Comment by MoonGoon72** [comment]
![랜딩페이지](https://user-images.githubusercontent.com/51581244/232260945-5c0758e3-f731-4862-94f5-4dbbcdb2cca7.png)
![13 Pro - 2](https://user-images.githubusercontent.com/51581244/232260978-7cca5ee1-5583-47ef-b7ea-88c00f9d9700.png)
어느 친구를 말하는것이지!

**Comment by YimKeul** [comment]
<img width="621" alt="스크린샷 2023-04-16 오후 12 47 12" src="https://user-images.githubusercontent.com/43426556/232265367-0e2a8dc5-4030-4f82-ac11-d550356adca7.png">
왼쪽에 이있는걸루
